dist: xenial
language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- python manage.py test
before_deploy:
  - bash gcloud-install.sh
deploy:
  provider: script
  script: bash gke-deploy.sh
  on:
    all_branches: true
